name: Build for Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install -U -r requirements.txt
        
    - name: Build executable
      run: |
        pyinstaller whisper_standalone.spec --clean
        
    - name: Rename executable with OS suffix
      run: |
        Rename-Item -Path "dist\whisper_standalone.exe" -NewName "whisper_standalone-windows.exe"

    - name: Install 7-Zip
      run: |
        choco install 7zip -y

    - name: Create ZIP Archive with 7-Zip
      run: |
        cd dist && 7z a -tzip "whisper_standalone-windows.zip" "whisper_standalone-windows.exe"

    - name: Create Release Asset
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag'
      with:
        files: dist/whisper_standalone-windows.zip
